## Feature Scaling

```
Features (independent) need to be in the same scale.

1) Min-Max Normalization
 
    Xnew = Xold - Xmin
           -----------
           Xmax - Xmin

2) Standadization 
    Xnew =  X - mu
            ------
            sigma
            
When to use feature scaling
1) Use of gradient descent (like deep leaning)
2) Use of distance calculating techniques (KNN, K-Means)
```



In [1]:
import numpy as np
             #height - mm, weight - kg
data = np.array([[168, 62],
                [172, 70],
                [180, 90],
                [192, 120],
                [178, 110]])

In [2]:
data

array([[168,  62],
       [172,  70],
       [180,  90],
       [192, 120],
       [178, 110]])

### Normalization

In [4]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler

scaler = MinMaxScaler()
min_max_scaled_data = scaler.fit_transform(data)
min_max_scaled_data

array([[0.        , 0.        ],
       [0.16666667, 0.13793103],
       [0.5       , 0.48275862],
       [1.        , 1.        ],
       [0.41666667, 0.82758621]])

### Standadization

In [5]:
scaler = StandardScaler()
standard_scaled_data = scaler.fit_transform(data)
standard_scaled_data

array([[-1.21987509, -1.27437573],
       [-0.73192505, -0.91539665],
       [ 0.24397502, -0.01794895],
       [ 1.70782513,  1.32822259],
       [ 0.        ,  0.87949874]])