In [1]:
import torch


In [2]:
tensor1=torch.tensor(8)

In [3]:
print(tensor1)

tensor(8)


In [4]:
print(tensor1.dtype)

torch.int64


In [8]:
tensor2 = torch.tensor([10,20.0,30,40])
print(tensor2)

tensor([10., 20., 30., 40.])


In [13]:
tensor2d = torch.tensor([[22,28],[45,85],[45,23]])
print(tensor2d)

tensor([[22, 28],
        [45, 85],
        [45, 23]])


In [15]:
tensor3d = torch.tensor ([
    [[20,40,60],[40,70,50]],
     [[200,400,600],[400,700,500]],
     [[78,40,60],[40,70,50]],

]
)
print(tensor3d)

tensor([[[ 20,  40,  60],
         [ 40,  70,  50]],

        [[200, 400, 600],
         [400, 700, 500]],

        [[ 78,  40,  60],
         [ 40,  70,  50]]])


In [16]:
streaming_service_list = ['netflix','hulu','prime video','HBO']
from sklearn import preprocessing
str = preprocessing.LabelEncoder()
targets = str.fit_transform(streaming_service_list)
tensorList = torch.as_tensor(targets)
print(tensorList)

tensor([2, 1, 3, 0])
